import type { GenerationModeId, ScriptId } from '@/types/project';
import { normalizeStyleDna, type StyleDna } from '@/types/styleDna';

export interface StylePreset {
  id: string;
  name: string;
  blurb: string;
  /** Scripts this hand suits best; the studio still allows any script. */
  bestFor: ScriptId[];
  suggestedMode: GenerationModeId;
  sampleText: Record<ScriptId, string>;
  swatches: string[];
  dna: StyleDna;
}

const preset = (
  meta: Omit<StylePreset, 'dna' | 'swatches'> & { swatches?: string[] },
  dna: Parameters<typeof normalizeStyleDna>[0],
): StylePreset => {
  const normalized = normalizeStyleDna(dna);
  return {
    ...meta,
    swatches: meta.swatches ?? [
      ...normalized.colorProfile.primaryColors.slice(0, 2),
      ...normalized.colorProfile.backgroundColors.slice(0, 2),
    ],
    dna: normalized,
  };
};

export const STYLE_PRESETS: StylePreset[] = [
  preset(
    {
      id: 'letterpress-vintage',
      name: 'Vintage letterpress',
      blurb: 'Heavy slab impression on cream stock, ink squeeze and paper tooth intact.',
      bestFor: ['Latin', 'Devanagari'],
      suggestedMode: 'faithful',
      sampleText: {
        Latin: 'HARVEST\nMARKET',
        Bengali: 'শুভ\nনববর্ষ',
        Devanagari: 'शुभ\nदीपावली',
      },
    },
    {
      detectedScript: 'Latin',
      detectedReferenceText: 'HARVEST MARKET',
      typographyCategory: 'vintage',
      strokeProfile: {
        averageStrokeWidth: 'heavy — around 18% of cap height',
        strokeContrast: 'low contrast, 1.6:1 thick-to-thin',
        pressureVariation: 'even, with ink squeeze thickening the stroke edges',
        edgeQuality: 'slightly rough where ink bit into the paper fibres',
        brushTexture: 'metal type pressed into damp stock',
      },
      formProfile: {
        xHeightOrScriptScale: 'large x-height, tightly stacked lines',
        curves: 'sturdy, squared curves',
        terminals: 'blunt slab serifs',
        ligatures: 'standard ligatures only',
        flourishes: 'none',
        slant: 'upright, 0°',
        baseline: 'rigid, level baseline',
      },
      colorProfile: {
        primaryColors: ['#2c2013', '#7a3b21'],
        secondaryColors: ['#a8642f'],
        gradientDescription: 'none — flat ink',
        shadowColor: 'none',
        outlineColor: 'none',
        backgroundColors: ['#efe4cd', '#e2d2b4'],
      },
      effectsProfile: {
        shadow: 'none',
        outline: 'none',
        glow: 'none',
        emboss: 'faint letterpress deboss inside the counters',
        inkBleed: 'ink feathers ~1% into the paper along every edge',
        paperTexture: 'cold-press cream stock with visible tooth',
        grain: 'fine, warm grain across the sheet',
        lighting: 'flat, even lighting',
      },
      compositionProfile: {
        layout: 'two stacked lines, generous margins, rule beneath',
        alignment: 'centred',
        margins: 'about 12% of the width',
        textHierarchy: 'two levels — dominant headline, smaller second line',
        decorativeElements: 'thin rule with a lozenge below the type',
      },
      renderHints: {
        fontCategory: 'slab',
        weight: 900,
        slantDegrees: 0,
        letterSpacingEm: 0.04,
        lineHeight: 0.98,
        strokeContrastRatio: 1.6,
        penAngleDegrees: 0,
        outlineWidthEm: 0,
        shadowOffsetEm: 0,
        shadowBlurEm: 0,
        embossStrength: 0.28,
        textureIntensity: 0.62,
        inkBleedAmount: 0.32,
        edgeRoughness: 0.3,
        uppercase: true,
        gradientKind: 'none',
        backgroundKind: 'linear',
        alignment: 'center',
        marginRatio: 0.12,
        hierarchyContrast: 0.62,
        ornamentation: 0.4,
        baselineJitterEm: 0.004,
      },
      generationPrompt:
        'Set the words as heavy slab-serif letterpress on damp cream stock. Ink squeeze thickens the edges, the paper tooth shows through, and a hairline rule with a lozenge sits under the block.',
      confidenceScore: 0.9,
      userWarnings: [],
    },
  ),
  preset(
    {
      id: 'neon-nights',
      name: 'Neon nights',
      blurb: 'Tube-bent script glowing off near-black, with a hot core and cool bloom.',
      bestFor: ['Latin', 'Devanagari', 'Bengali'],
      suggestedMode: 'faithful',
      sampleText: {
        Latin: 'midnight\ndiner',
        Bengali: 'রাতের\nশহর',
        Devanagari: 'रात की\nरोशनी',
      },
    },
    {
      detectedScript: 'Latin',
      detectedReferenceText: 'midnight diner',
      typographyCategory: 'neon',
      strokeProfile: {
        averageStrokeWidth: 'medium, monoline — about 7% of cap height',
        strokeContrast: 'monoline, 1:1 — bent glass tube',
        pressureVariation: 'none, constant tube diameter',
        edgeQuality: 'crisp core with a soft luminous halo',
        brushTexture: 'none — glass tubing',
      },
      formProfile: {
        xHeightOrScriptScale: 'tall ascenders, connected script',
        curves: 'smooth continuous curves, tube-bent',
        terminals: 'rounded tube ends',
        ligatures: 'flowing connections between letters',
        flourishes: 'long entry and exit strokes',
        slant: '12° to the right',
        baseline: 'gently bouncing baseline',
      },
      colorProfile: {
        primaryColors: ['#ff5ea8', '#ffd6e8'],
        secondaryColors: ['#66e0ff'],
        gradientDescription: 'linear gradient along the stroke from hot pink into pale rose',
        shadowColor: 'none',
        outlineColor: 'none',
        backgroundColors: ['#141322', '#05050a'],
      },
      effectsProfile: {
        shadow: 'none',
        outline: 'none',
        glow: 'strong bloom, roughly 30% of cap height, doubled near the core',
        emboss: 'none',
        inkBleed: 'none',
        paperTexture: 'none',
        grain: 'subtle sensor grain in the dark field',
        lighting: 'the lettering is the only light source',
      },
      compositionProfile: {
        layout: 'two script lines centred in a dark field',
        alignment: 'centred',
        margins: 'about 14% of the width',
        textHierarchy: 'two levels',
        decorativeElements: 'none',
      },
      renderHints: {
        fontCategory: 'script',
        weight: 400,
        slantDegrees: 12,
        letterSpacingEm: 0.01,
        lineHeight: 1.02,
        strokeContrastRatio: 1.1,
        penAngleDegrees: 0,
        outlineWidthEm: 0,
        shadowOffsetEm: 0,
        shadowBlurEm: 0,
        glowRadiusEm: 0.32,
        embossStrength: 0,
        textureIntensity: 0.18,
        inkBleedAmount: 0,
        edgeRoughness: 0,
        uppercase: false,
        gradientKind: 'linear',
        gradientAngleDegrees: 70,
        backgroundKind: 'radial',
        alignment: 'center',
        marginRatio: 0.14,
        hierarchyContrast: 0.7,
        ornamentation: 0.1,
        baselineJitterEm: 0.012,
      },
      generationPrompt:
        'Bend the words as a single neon tube: monoline strokes, rounded tube ends, hot pink core fading to pale rose, a wide luminous bloom on near-black, and nothing else in the frame.',
      confidenceScore: 0.9,
      userWarnings: [],
    },
  ),
  preset(
    {
      id: 'wet-brush-bengali',
      name: 'Wet brush Bangla',
      blurb: 'Loaded flat brush, indigo ink pooling into handmade paper.',
      bestFor: ['Bengali'],
      suggestedMode: 'artistic',
      sampleText: {
        Latin: 'monsoon\nsongs',
        Bengali: 'আমি বাংলায়\nগান গাই',
        Devanagari: 'बरसात के\nगीत',
      },
    },
    {
      detectedScript: 'Bengali',
      detectedReferenceText: 'আমি বাংলায় গান গাই',
      typographyCategory: 'brush',
      strokeProfile: {
        averageStrokeWidth: 'bold — 14% of the line height, matra heavier still',
        strokeContrast: 'high contrast, 3.6:1 thick-to-thin',
        pressureVariation: 'strong swell in the middle of each stroke, dry at the tail',
        edgeQuality: 'rough, dry-brush edges that break up along the stroke',
        brushTexture: 'flat brush loaded with ink, dry at the tail',
      },
      formProfile: {
        xHeightOrScriptScale: 'heavy continuous matra, generous kar signs',
        curves: 'organic, hand-drawn curves with uneven tension',
        terminals: 'frayed, brush-swept terminals',
        ligatures: 'juktakkhor drawn as single confident gestures',
        flourishes: 'sweeping exit stroke under the line',
        slant: '6° to the right',
        baseline: 'slightly bouncing baseline, hand-set feel',
      },
      colorProfile: {
        primaryColors: ['#1d2b53', '#2f4a86'],
        secondaryColors: ['#8c5a2b'],
        gradientDescription: 'none — flat ink with tonal variation from the brush load',
        shadowColor: 'none',
        outlineColor: 'none',
        backgroundColors: ['#f2ece0', '#e6dbc7'],
      },
      effectsProfile: {
        shadow: 'none',
        outline: 'none',
        glow: 'none',
        emboss: 'none',
        inkBleed: 'ink spreads visibly into the paper fibres, ~45% edge break-up',
        paperTexture: 'handmade rag paper with pronounced tooth',
        grain: 'moderate paper grain',
        lighting: 'soft, diffuse daylight',
      },
      compositionProfile: {
        layout: 'two lines of brush lettering with a swash beneath',
        alignment: 'centred',
        margins: 'about 10% of the width',
        textHierarchy: 'one dominant level with a lighter second line',
        decorativeElements: 'single calligraphic swash flourish under the block',
      },
      renderHints: {
        fontCategory: 'brush',
        weight: 400,
        slantDegrees: 6,
        letterSpacingEm: 0.015,
        lineHeight: 1.16,
        strokeContrastRatio: 3.6,
        penAngleDegrees: 28,
        outlineWidthEm: 0,
        shadowOffsetEm: 0,
        shadowBlurEm: 0,
        embossStrength: 0,
        textureIntensity: 0.72,
        inkBleedAmount: 0.55,
        edgeRoughness: 0.52,
        uppercase: false,
        gradientKind: 'none',
        backgroundKind: 'linear',
        alignment: 'center',
        marginRatio: 0.1,
        hierarchyContrast: 0.66,
        ornamentation: 0.55,
        baselineJitterEm: 0.02,
      },
      generationPrompt:
        'Letter the words with a flat brush loaded with indigo ink on handmade rag paper: heavy continuous headline stroke, strong pressure swell, dry frayed tails, ink bleeding into the fibres, and one sweeping swash beneath the block.',
      confidenceScore: 0.9,
      userWarnings: [],
    },
  ),
  preset(
    {
      id: 'gold-wedding-devanagari',
      name: 'Gold invitation',
      blurb: 'High-contrast didone Devanagari in gold leaf on deep maroon.',
      bestFor: ['Devanagari', 'Latin'],
      suggestedMode: 'faithful',
      sampleText: {
        Latin: 'Anand &\nMeera',
        Bengali: 'শুভ\nবিবাহ',
        Devanagari: 'शुभ विवाह\nनिमंत्रण',
      },
    },
    {
      detectedScript: 'Devanagari',
      detectedReferenceText: 'शुभ विवाह',
      typographyCategory: 'decorative',
      strokeProfile: {
        averageStrokeWidth: 'medium — 9% of the line height with a crisp thin axis',
        strokeContrast: 'extreme didone-like contrast, 5.4:1 thick-to-thin',
        pressureVariation: 'sharp transitions between stems and hairlines',
        edgeQuality: 'crisp, vector-clean edges',
        brushTexture: 'none — engraved, foil-stamped',
      },
      formProfile: {
        xHeightOrScriptScale: 'tall, elegant proportions with a fine shirorekha',
        curves: 'controlled curves with even tension',
        terminals: 'finely tapered terminals',
        ligatures: 'traditional conjuncts, tightly fitted',
        flourishes: 'small ornamental spurs at the line ends',
        slant: 'upright, 0°',
        baseline: 'rigid, level baseline',
      },
      colorProfile: {
        primaryColors: ['#e6c07a', '#f6e5b8'],
        secondaryColors: ['#c39a4b'],
        gradientDescription: 'linear gradient across the lettering at 100°, imitating foil sheen',
        shadowColor: '#1a0508',
        outlineColor: 'none',
        backgroundColors: ['#4a0d1a', '#2a060e'],
      },
      effectsProfile: {
        shadow: 'tight offset shadow, 4% of the em, low blur',
        outline: 'none',
        glow: 'none',
        emboss: 'foil emboss on the thick stems',
        inkBleed: 'none',
        paperTexture: 'smooth cotton card',
        grain: 'very fine grain',
        lighting: 'raking light from the upper left catching the foil',
      },
      compositionProfile: {
        layout: 'centred block inside an inset frame',
        alignment: 'centred',
        margins: 'about 15% of the width',
        textHierarchy: 'two levels',
        decorativeElements: 'inset frame with corner brackets and a rule',
      },
      renderHints: {
        fontCategory: 'display',
        weight: 400,
        slantDegrees: 0,
        letterSpacingEm: 0.05,
        lineHeight: 1.18,
        strokeContrastRatio: 5.4,
        penAngleDegrees: 0,
        outlineWidthEm: 0,
        shadowOffsetEm: 0.035,
        shadowBlurEm: 0.03,
        shadowAngleDegrees: 55,
        embossStrength: 0.45,
        textureIntensity: 0.2,
        inkBleedAmount: 0,
        edgeRoughness: 0,
        uppercase: false,
        gradientKind: 'linear',
        gradientAngleDegrees: 100,
        backgroundKind: 'radial',
        alignment: 'center',
        marginRatio: 0.15,
        hierarchyContrast: 0.58,
        ornamentation: 0.85,
        baselineJitterEm: 0,
      },
      generationPrompt:
        'Foil-stamp the words in gold on deep maroon cotton card: extreme thick-to-thin contrast, fine hairlines, a sheen gradient across the stems, a tight offset shadow, and an inset frame with corner brackets.',
      confidenceScore: 0.9,
      userWarnings: [],
    },
  ),
  preset(
    {
      id: 'swiss-poster',
      name: 'Swiss grid',
      blurb: 'Condensed grotesque, flush left, one red accent. No ornament, no apology.',
      bestFor: ['Latin', 'Devanagari', 'Bengali'],
      suggestedMode: 'clean-poster',
      sampleText: {
        Latin: 'TYPE\nMATTERS',
        Bengali: 'নতুন\nদৃষ্টি',
        Devanagari: 'नई\nदृष्टि',
      },
    },
    {
      detectedScript: 'Latin',
      detectedReferenceText: 'TYPE MATTERS',
      typographyCategory: 'sans-serif',
      strokeProfile: {
        averageStrokeWidth: 'bold — 15% of cap height',
        strokeContrast: 'monoline, 1:1',
        pressureVariation: 'none',
        edgeQuality: 'crisp, vector-clean edges',
        brushTexture: 'none — smooth digital strokes',
      },
      formProfile: {
        xHeightOrScriptScale: 'very large x-height, narrow set width',
        curves: 'geometric curves with even tension',
        terminals: 'horizontally sheared terminals',
        ligatures: 'none',
        flourishes: 'none',
        slant: 'upright, 0°',
        baseline: 'rigid, level baseline',
      },
      colorProfile: {
        primaryColors: ['#101014', '#e2231a'],
        secondaryColors: ['#e2231a'],
        gradientDescription: 'none — flat colour',
        shadowColor: 'none',
        outlineColor: 'none',
        backgroundColors: ['#f4f4f2'],
      },
      effectsProfile: {
        shadow: 'none',
        outline: 'none',
        glow: 'none',
        emboss: 'none',
        inkBleed: 'none',
        paperTexture: 'none',
        grain: 'none',
        lighting: 'flat, even lighting',
      },
      compositionProfile: {
        layout: 'flush-left stack pinned to a 12-column grid',
        alignment: 'left',
        margins: 'tight — about 7% of the width',
        textHierarchy: 'one dominant level',
        decorativeElements: 'none',
      },
      renderHints: {
        fontCategory: 'sans',
        weight: 700,
        slantDegrees: 0,
        letterSpacingEm: -0.02,
        lineHeight: 0.92,
        strokeContrastRatio: 1,
        penAngleDegrees: 0,
        outlineWidthEm: 0,
        shadowOffsetEm: 0,
        shadowBlurEm: 0,
        embossStrength: 0,
        textureIntensity: 0,
        inkBleedAmount: 0,
        edgeRoughness: 0,
        uppercase: true,
        gradientKind: 'none',
        backgroundKind: 'flat',
        alignment: 'left',
        marginRatio: 0.07,
        hierarchyContrast: 1,
        ornamentation: 0,
        baselineJitterEm: 0,
      },
      generationPrompt:
        'Set the words as a condensed grotesque locked to a grid: flush left, very tight leading, monoline strokes, near-black on off-white with a single red accent, and absolutely no ornament or texture.',
      confidenceScore: 0.9,
      userWarnings: [],
    },
  ),
  preset(
    {
      id: 'copperplate-invite',
      name: 'Copperplate hand',
      blurb: 'Pointed-nib formal script, hairline entries, generous swashes on ivory.',
      bestFor: ['Latin'],
      suggestedMode: 'artistic',
      sampleText: {
        Latin: 'Save the\nDate',
        Bengali: 'শুভ\nপরিণয়',
        Devanagari: 'शुभ\nपरिणय',
      },
    },
    {
      detectedScript: 'Latin',
      detectedReferenceText: 'Save the Date',
      typographyCategory: 'calligraphic',
      strokeProfile: {
        averageStrokeWidth: 'light — 5% of cap height on the shades, hairline on the connectors',
        strokeContrast: 'extreme contrast, 6:1 thick-to-thin',
        pressureVariation: 'pointed nib opening on every downstroke, hairline on the way up',
        edgeQuality: 'crisp with a faint ink halo',
        brushTexture: 'pointed nib with strong pressure modulation',
      },
      formProfile: {
        xHeightOrScriptScale: 'small x-height, tall looping ascenders',
        curves: 'oval, tightly controlled copperplate curves',
        terminals: 'hairline entries and exits',
        ligatures: 'fully connected script',
        flourishes: 'generous swashes on the ascenders and the final stroke',
        slant: '35° to the right',
        baseline: 'rigid baseline with a 55° slant grid',
      },
      colorProfile: {
        primaryColors: ['#232028'],
        secondaryColors: ['#8a7a5c'],
        gradientDescription: 'none — flat iron-gall ink',
        shadowColor: 'none',
        outlineColor: 'none',
        backgroundColors: ['#fbf7ee', '#f1e9d8'],
      },
      effectsProfile: {
        shadow: 'none',
        outline: 'none',
        glow: 'none',
        emboss: 'none',
        inkBleed: 'very slight feathering where the nib paused',
        paperTexture: 'smooth ivory laid paper',
        grain: 'fine grain',
        lighting: 'soft, even studio light',
      },
      compositionProfile: {
        layout: 'two centred script lines with a long flourish beneath',
        alignment: 'centred',
        margins: 'generous — about 16% of the width',
        textHierarchy: 'two levels',
        decorativeElements: 'long calligraphic swash and a small rule',
      },
      renderHints: {
        fontCategory: 'script',
        weight: 400,
        slantDegrees: 30,
        letterSpacingEm: 0,
        lineHeight: 1.05,
        strokeContrastRatio: 6,
        penAngleDegrees: 55,
        outlineWidthEm: 0,
        shadowOffsetEm: 0,
        shadowBlurEm: 0,
        embossStrength: 0,
        textureIntensity: 0.28,
        inkBleedAmount: 0.16,
        edgeRoughness: 0.1,
        uppercase: false,
        gradientKind: 'none',
        backgroundKind: 'linear',
        alignment: 'center',
        marginRatio: 0.16,
        hierarchyContrast: 0.6,
        ornamentation: 0.7,
        baselineJitterEm: 0,
      },
      generationPrompt:
        'Write the words with a pointed nib in the copperplate hand: 55° slant grid, hairline entries swelling into full shades, fully connected letters, tall looping ascenders with swashes, iron-gall ink on ivory laid paper.',
      confidenceScore: 0.9,
      userWarnings: [],
    },
  ),
];

export const presetById = (id: string): StylePreset | undefined =>
  STYLE_PRESETS.find((entry) => entry.id === id);
