/**
 * Vendors the bundled type library from the google/fonts repository.
 *
 *   npm run fonts:fetch
 *
 * Writes
 *   public/fonts/<Face>.ttf
 *   public/fonts/licenses/<id>.OFL.txt
 *   public/fonts/fonts.css              @font-face declarations
 *   src/generated/font-manifest.json    metadata consumed by the render engine
 *
 * Downloads go through raw.githubusercontent.com; if plain HTTPS is blocked the
 * script falls back to the GitHub CLI (`gh api`), which is handy on locked-down
 * build machines.
 */
import { execFile } from 'node:child_process';
import { existsSync, mkdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import { FONTS, isVariable } from './font-manifest.mjs';

const execFileAsync = promisify(execFile);
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const fontsDir = join(root, 'public', 'fonts');
const licenseDir = join(fontsDir, 'licenses');
const generatedDir = join(root, 'src', 'generated');
const REPO = 'google/fonts';
const BRANCH = 'main';
const force = process.argv.includes('--force');

for (const dir of [fontsDir, licenseDir, generatedDir]) mkdirSync(dir, { recursive: true });

async function downloadViaHttps(path) {
  const url = `https://raw.githubusercontent.com/${REPO}/${BRANCH}/${path.split('/').map(encodeURIComponent).join('/')}`;
  const response = await fetch(url);
  if (!response.ok) throw new Error(`HTTP ${response.status} for ${url}`);
  return Buffer.from(await response.arrayBuffer());
}

async function downloadViaGh(path) {
  // Variable-font filenames contain [] which must be percent-encoded for the API path.
  const apiPath = path.replace(/\[/g, '%5B').replace(/\]/g, '%5D');
  const { stdout } = await execFileAsync(
    'gh',
    ['api', '-H', 'Accept: application/vnd.github.raw', `repos/${REPO}/contents/${apiPath}`],
    { maxBuffer: 64 * 1024 * 1024, encoding: 'buffer' },
  );
  return Buffer.from(stdout);
}

async function download(path) {
  try {
    return await downloadViaHttps(path);
  } catch (httpsError) {
    try {
      return await downloadViaGh(path);
    } catch (ghError) {
      throw new Error(
        `Could not fetch ${path}.\n  https: ${httpsError.message}\n  gh:    ${ghError.message}`,
      );
    }
  }
}

const isTtf = (buffer) => {
  if (buffer.length < 4) return false;
  const tag = buffer.readUInt32BE(0);
  return tag === 0x00010000 || tag === 0x74727565 || tag === 0x4f54544f || tag === 0x74746366;
};

let downloaded = 0;
let skipped = 0;
let bytes = 0;

for (const font of FONTS) {
  const target = join(fontsDir, font.out);
  if (!force && existsSync(target) && statSync(target).size > 1024) {
    bytes += statSync(target).size;
    skipped += 1;
    continue;
  }
  process.stdout.write(`  ↓ ${font.family.padEnd(34)} `);
  const buffer = await download(`${font.dir}/${font.file}`);
  if (!isTtf(buffer)) {
    throw new Error(`${font.file} does not look like a TrueType/OpenType file.`);
  }
  writeFileSync(target, buffer);
  bytes += buffer.length;
  downloaded += 1;
  console.log(`${(buffer.length / 1024).toFixed(0)} KB`);

  const license = await download(`${font.dir}/OFL.txt`);
  writeFileSync(join(licenseDir, `${font.id}.OFL.txt`), license);
}

/* ------------------------------------------------------------------ fonts.css */

const faceBlocks = FONTS.map((font) => {
  const weight = isVariable(font) ? `${font.weight[0]} ${font.weight[1]}` : `${font.weight[0]}`;
  return `/* ${font.family} — ${font.note} */
@font-face {
  font-family: '${font.family}';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url('./${font.out}') format('truetype${isVariable(font) ? '-variations' : ''}');
}`;
}).join('\n\n');

writeFileSync(
  join(fontsDir, 'fonts.css'),
  `/* -----------------------------------------------------------------------------
 * GlyphAura Studio — bundled type library
 * GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
 *
 * Every face below is licensed under the SIL Open Font License 1.1.
 * Full license texts live in ./licenses/.
 * -------------------------------------------------------------------------- */

${faceBlocks}

/* Interface stack: native Apple system text first, bundled Inter as the
   cross-platform fallback so the studio looks identical everywhere. */
:root {
  --ga-font-ui: -apple-system, BlinkMacSystemFont, 'SF Pro Text', 'SF Pro Display',
    'Inter Variable', 'Helvetica Neue', Helvetica, Arial, sans-serif;
}
`,
  'utf8',
);

/* --------------------------------------------------------- font-manifest.json */

const manifest = {
  generatedBy: 'scripts/fetch-fonts.mjs',
  source: `https://github.com/${REPO}/tree/${BRANCH}`,
  license: 'SIL Open Font License 1.1',
  fontCount: FONTS.length,
  fonts: FONTS.map((font) => ({
    id: font.id,
    family: font.family,
    file: `/fonts/${font.out}`,
    scripts: font.scripts,
    category: font.category,
    contrast: font.contrast,
    weightMin: font.weight[0],
    weightMax: font.weight[1],
    variable: isVariable(font),
    caps: font.caps,
    optical: font.optical,
    tags: font.tags,
    note: font.note,
    licenseFile: `/fonts/licenses/${font.id}.OFL.txt`,
    upstream: `https://github.com/${REPO}/tree/${BRANCH}/${font.dir}`,
  })),
};

writeFileSync(
  join(generatedDir, 'font-manifest.ts'),
  `/* eslint-disable */
/**
 * GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
 * Run \`npm run fonts:fetch\` to refresh.
 *
 * Emitted as TypeScript rather than JSON so it can be imported identically by
 * Vite, tsc and the dependency-free Node test runner.
 */
export const FONT_MANIFEST = ${JSON.stringify(manifest, null, 2)};
`,
  'utf8',
);

console.log(
  `\n  ${downloaded} downloaded, ${skipped} already present — ${(bytes / (1024 * 1024)).toFixed(1)} MB total`,
);
console.log('  wrote public/fonts/fonts.css and src/generated/font-manifest.ts\n');
